name: Ensure Arma.Demo.Core Builds

on:
  push:
    branches:
      - main
    paths:
      - src/Arma.Demo.Core/*
  pull_request:
    branches:
      - main
    paths:
      - src/Arma.Demo.Core/*
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Arma.Demo.Core/
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build -c Release