name: Pack and Push Arma.Demo.Core to NuGet

on:
  push:
    branches:
      - main
    paths:
      - src/Arma.Demo.Core/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Push to NuGet
      run: dotnet nuget push Arma.Demo.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}